export default (appConfig = {
  listRooms: [
    {
      id: '18',
      roomName: '18',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '', // DG/CD/QD
      sectionRoom: '', // quat/lanh
      overnight_price: 120,
      type: '1bed',
      cmnd: null
    },
    {
      id: '9',
      roomName: '9',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 180,
      type: 'special',
      cmnd: null
    },
    {
      id: '10',
      roomName: '10',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 180,
      type: 'special',
      cmnd: null
    },
    {
      id: '11',
      roomName: '11',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 220,
      type: '2beds',
      cmnd: null
    },
    {
      id: '12',
      roomName: '12',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 220,
      type: '2beds',
      cmnd: null
    },
    {
      id: '13',
      roomName: '13',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 180,
      type: 'special',
      cmnd: null
    },
    {
      id: '14',
      roomName: '14',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 180,
      type: 'special',
      cmnd: null
    },
    {
      id: '15',
      roomName: '15',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 180,
      type: 'special',
      cmnd: null
    },
    {
      id: '16',
      roomName: '16',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 200,
      type: 'special',
      cmnd: null
    },
    {
      id: '17',
      roomName: '17',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 180,
      type: '1bed',
      cmnd: null
    },
    {
      id: '8',
      roomName: '8',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 120,
      type: '1bed',
      cmnd: null
    },
    {
      id: '7',
      roomName: '7',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 180,
      type: 'special',
      cmnd: null
    },
    {
      id: '6',
      roomName: '6',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 220,
      type: '2beds',
      cmnd: null
    },
    {
      id: '5',
      roomName: '5',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 220,
      type: '2beds',
      cmnd: null
    },
    {
      id: '4',
      roomName: '4',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 180,
      type: 'special',
      cmnd: null
    },
    {
      id: '3',
      roomName: '3',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 180,
      type: 'special',
      cmnd: null
    },
    {
      id: '2',
      roomName: '2',
      currentStatus: 'available',
      timeIn: 0,
      chargedItems: [],
      note: '',
      tag: '',
      sectionRoom: '',
      overnight_price: 200,
      type: 'special',
      cmnd: null
    }
  ],
  bufferTimeInMinutes: 30,
  limitHourSectionTimeInHour: 3,
  limitHourSectionToOvernightInHour: 6,
  fanSectionPrice: 60,
  airSectionPrice: 100,
  fanHourAdditionalPrice: 20,
  airHourAdditionalPrice: 30,
  unitWaterPrice: 5,
  unitSoftDrinkPrice: 15,
  unitBeerPrice: 15,
  unitInstantNoodle: 15
})