export default (constants = {
    //Font
    Poppins_Bold: 'Poppins-Bold',
    Poppins_Medium: 'Poppins-Medium',
    Poppins_Regular:'Poppins-Regular',
    Poppins_SemiBold:'Poppins-SemiBold',
    Poppins_Italic:'Poppins-Italic',

    //Screen
    Welcome:'Welcome',
    Registration:'Registration',
    VerifySignup:'VerifySignup',
    VerifyLogin:'VerifyLogin',
    Fingerprint:'Fingerprint',
    Congratulation:'Congratulation',
    Login:'Login',
    TabNavigation:'TabNavigation',
    Setting:'Setting',
    Languages:'Languages',
    ProfileTab:'ProfileTab',
    Notification:'Notification',
    CardDetail:'CardDetail',
    RecentOrders:'RecentOrders',
    InviteFriend:'InviteFriend',
    BarCodeScanner:'BarCodeScanner',
    OrderDetail:'OrderDetail',
    MyRewards:'MyRewards',
    SpecialToday:'SpecialToday',
    SpecialDetail:'SpecialDetail',
    Menu:'Menu',
    PayScan:'PayScan',
    MemberShipInfo: 'MemberShipInfo',
    ExpenseStatistics:'ExpenseStatistics',
    PaymentDetail:'PaymentDetail',
    PaymentSuccess:'PaymentSuccess',
    Card:'Card',
    FoodsDetail: 'FoodsDetail',
    HomeTab: 'HomeTab',
    StoreDetail: 'StoreDetail',
    PopularList: 'PopularList',
    Cards: 'Home',

    //Storage
    isTouchId: 'TouchId',
    username:'Username',
    fullName:'FullName',
    User_id: 'UserId',
    Language: 'Language',
    SecondStart:'SecondStart',

})