//===================================LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//===================================HOME
export const GET_ROOMS_DATA_REQUEST = 'GET_ROOMS_DATA_REQUEST';
export const GET_ROOMS_DATA_SUCCESS = 'GET_ROOMS_DATA_SUCCESS';
export const GET_ROOMS_DATA_FAILURE = 'GET_ROOMS_DATA_FAILURE';

//===================================GET_ROOM
export const GET_ROOM_INFO_REQUEST = 'GET_ROOM_INFO_REQUEST';
export const GET_ROOM_INFO_SUCCESS = 'GET_ROOM_INFO_SUCCESS';
export const GET_ROOM_INFO_FAILURE = 'GET_ROOM_INFO_FAILURE';

//===================================UPDATE_ROOM
export const UPDATE_ROOM_INFO_REQUEST = 'UPDATE_ROOM_INFO_REQUEST';
export const UPDATE_ROOM_INFO_SUCCESS = 'UPDATE_ROOM_INFO_SUCCESS';
export const UPDATE_ROOM_INFO_FAILURE = 'UPDATE_ROOM_INFO_FAILURE';

//===================================ADD_CHARGED_ITEM
export const ADD_CHARGED_ITEM_REQUEST = 'ADD_CHARGED_ITEM_REQUEST';
export const ADD_CHARGED_ITEM_SUCCESS = 'ADD_CHARGED_ITEM_SUCCESS';
export const ADD_CHARGED_ITEM_FAILURE = 'ADD_CHARGED_ITEM_FAILURE';

//===================================UPDATE_CHARGED_ITEM
export const UPDATE_CHARGED_ITEM_REQUEST = 'UPDATE_CHARGED_ITEM_REQUEST';
export const UPDATE_CHARGED_ITEM_SUCCESS = 'UPDATE_CHARGED_ITEM_SUCCESS';
export const UPDATE_CHARGED_ITEM_FAILURE = 'UPDATE_CHARGED_ITEM_FAILURE';

//===================================GET_CASH_BOX
export const GET_CASH_BOX_REQUEST = 'GET_CASH_BOX_REQUEST';
export const GET_CASH_BOX_SUCCESS = 'GET_CASH_BOX_SUCCESS';
export const GET_CASH_BOX_FAILURE = 'GET_CASH_BOX_FAILURE';

//===================================UPDATE_CASH_BOX
export const UPDATE_CASH_BOX_REQUEST = 'UPDATE_CASH_BOX_REQUEST';
export const UPDATE_CASH_BOX_SUCCESS = 'UPDATE_CASH_BOX_SUCCESS';
export const UPDATE_CASH_BOX_FAILURE = 'UPDATE_CASH_BOX_FAILURE';

//===================================ADD_HISTORY_ITEM
export const ADD_HISTORY_ITEM_REQUEST = 'ADD_HISTORY_ITEM_REQUEST';
export const ADD_HISTORY_ITEM_SUCCESS = 'ADD_HISTORY_ITEM_SUCCESS';
export const ADD_HISTORY_ITEM_FAILURE = 'ADD_HISTORY_ITEM_FAILURE';

//===================================GET_HISTORY_LIST
export const GET_HISTORY_LIST_REQUEST = 'GET_HISTORY_LIST_REQUEST';
export const GET_HISTORY_LIST_SUCCESS = 'GET_HISTORY_LIST_SUCCESS';
export const GET_HISTORY_LIST_FAILURE = 'GET_HISTORY_LIST_FAILURE';

//===================================GET_STATISTIC_OF_DAY
export const GET_STATISTIC_OF_DAY_REQUEST = 'GET_STATISTIC_OF_DAY_REQUEST';
export const GET_STATISTIC_OF_DAY_SUCCESS = 'GET_STATISTIC_OF_DAY_SUCCESS';
export const GET_STATISTIC_OF_DAY_FAILURE = 'GET_STATISTIC_OF_DAY_FAILURE';

//=================================== UPDATE HISTORY ROOM ITEM
export const UPDATE_HISTORY_ROOM_REQUEST = 'UPDATE_HISTORY_ROOM_REQUEST';
export const UPDATE_HISTORY_ROOM_SUCCESS = 'UPDATE_HISTORY_ROOM_SUCCESS';
export const UPDATE_HISTORY_ROOM_FAILURE = 'UPDATE_HISTORY_ROOM_FAILURE';

//=================================== GET_HISTORY_WITHDRAW_DEPOSIT
export const GET_HISTORY_WITHDRAW_DEPOSIT_REQUEST = 'GET_HISTORY_WITHDRAW_DEPOSIT_REQUEST';
export const GET_HISTORY_WITHDRAW_DEPOSIT_SUCCESS = 'GET_HISTORY_WITHDRAW_DEPOSIT_SUCCESS';
export const GET_HISTORY_WITHDRAW_DEPOSIT_FAILURE = 'GET_HISTORY_WITHDRAW_DEPOSIT_FAILURE';

//=================================== DELETE_HISTORY_WITHDRAW_DEPOSIT
export const DELETE_HISTORY_WITHDRAW_DEPOSIT_REQUEST = 'DELETE_HISTORY_WITHDRAW_DEPOSIT_REQUEST';
export const DELETE_HISTORY_WITHDRAW_DEPOSIT_SUCCESS = 'DELETE_HISTORY_WITHDRAW_DEPOSIT_SUCCESS';
export const DELETE_HISTORY_WITHDRAW_DEPOSIT_FAILURE = 'DELETE_HISTORY_WITHDRAW_DEPOSIT_FAILURE';

//=================================== CANCEL_CURRENT_ROOM
export const CANCEL_CURRENT_ROOM_REQUEST = 'CANCEL_CURRENT_ROOM_REQUEST';
export const CANCEL_CURRENT_ROOM_SUCCESS = 'CANCEL_CURRENT_ROOM_SUCCESS';
export const CANCEL_CURRENT_ROOM_FAILURE = 'CANCEL_CURRENT_ROOM_FAILURE';